GET http://localhost:8080/blogs

###

POST http://localhost:8080/blogs
content-type: application/json


{
    "title": "sample",
    "content": "sample",
    "summary": "test",
    "date": "2"
}

###

DELETE http://localhost:8080/blogs

